server:  
  port: 8058
 
spring:
  application:
    name: moviesclient
 
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
microservicio:
  movie:
    name: api-gateway
    addUrl: http://${microservicio.contact.name}/movies
    getAllUrl: http://${microservicio.contact.name}/movies
    getByIdUrl: http://${microservicio.contact.name}/movies/{id}
    getByCategory: http://${microservicio.contact.name}/movies/categorias/{categoria}
    updateUrl: http://${microservicio.contact.name}/movies/{id}
    deleteUrl: http://${microservicio.contact.name}/movies/{id}
    
